### ISSUE TITLE
Sample for RestConnector

### ISSUE THREAD

**Issue by ryanmaule** [nathangiusti/PySense#16]
I'm having trouble getting RestConnector to work, and an example would be very helpful!

Here's a rough example of what I'm trying to do, sending a JAQL query to an elasticube.

`
bearer_token = {'authorization':'Bearer xxx'}

rest_connector = PySenseRestConnector.RestConnector('https://ourdomain.com',False,False,bearer_token)

jaql_query = rest_connector.rest_call('post', 'api/elasticubes/my_cube/jaql', my_jaql) 
`

However I'm getting a number of errors, likely due to my own mistakes.  In the above example I get the error that rest_call expects 3 arguments but 4 were given.  If I remove my_jaql I get an error that path should be a string, not dict.

**Comment by nathangiusti** [comment]
Hi Ryan, 

I added this functionality primarily to facilitate the creation of a load tester. https://github.com/nathangiusti/SisenseLoadTest

This is the only place where I have implemented the functionality.
