### ISSUE TITLE
YAML Template Missing

### ISSUE THREAD

**Issue by davesgonechina** [nathangiusti/PySense#3]
I'd like to try this script but cannot find a template for this YAML config.

https://github.com/nathangiusti/PySense/blob/56671f41674046ac0b90a56dfc9b4561754c9857/Scripts/Reports/TableConfigReport.py#L11

**Comment by nathangiusti** [comment]
https://github.com/nathangiusti/PySense/blob/master/Snippets/SampleConfig.yaml

**Comment by davesgonechina** [comment]
Thanks!
