### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by davesgonechina** [nathangiusti/PySense#5]
Cannot log in with username/password, Sisense support suggested that because my user is non-admin I must use an API token. I have one but YAML lacks fields and documentation on how to authenticate. Unsure if this is the block or something else, like an IP whitelisting.

https://github.com/nathangiusti/PySense/blob/87d55f2f0e078aa9dc84932ed618a41966a8ee53/Snippets/SampleConfig.yaml#L2

**Comment by nathangiusti** [comment]
I'll add functionality to accept a bearer token. It's been added to the backlog.
